- hosts:  tag_Name_dev   #amazon linux instance  package manager = yum 
  become: true 
  gather_facts: true 
  ignore_errors: true
  tasks:
   - name: Install apache web server on all dev instances-hosts
     yum:  name=httpd state=latest 
     tags:
     - install 
   - name: start the apache websserver 
     service: name=httpd state=started
     tags:
      - start 
   - name: copy files to index.html 
     copy:
      src: /home/liontechnologyies/april22/index.html
      dest: /var/www/html/index.html 
   - name: debug  the playbook and run and also print the messages
     debug: 
       msg: "from Lion Tech DevOps engineer, keep on the good work"
   - name: restart the apache websserver  
     service: name=httpd state=restarted
   - name: create a file 
     shell:  echo "welcome to the devops world"  > welcome.txt 