- hosts: tag_Name_staging
  remote_user: ec2-user
  gather_facts: yes
  tasks:
   - name:  Testing Remote connection with staging servers
     ping:
     remote_user: ec2-user

#how to execute this playbook
# ansible-playbook --f ping:staging.yaml