---
- name: Linux Reboot Demo
  hosts: tag_Name_prod
  gather_facts: no
  remote_user: billy
  become: true

  tasks:
    - name: Reboot the machine (Wait for 5 min)
      reboot:
        reboot_timeout: 300